name: Java CI

on: [push]

jobs:
  backend:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.10'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Testing
        run: mvn surefire:test
  frontend:
    runs-on: ubuntu-latest
    env:
      frontend-dictionary: './src/main/webapp/front-product-management'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Build with NPM
      - run: npm install
        working-directory: ${{env.frontend-dictionary}}
      - name: Testng
      - run: npm test
        working-directory: ${{env.frontend-dictionary}}

